// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2w4ckCR4u3W0Hw4VEbRdBF9erH7EPjs',
    appId: '1:140590274669:android:66aff9fdb2f52adb7ec764',
    messagingSenderId: '140590274669',
    projectId: 'arzan-app',
    storageBucket: 'arzan-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdS5LYfjfI8EJAbtsh6i69Tl6uVkBsk2E',
    appId: '1:140590274669:ios:63f7b1bb16c20b8f7ec764',
    messagingSenderId: '140590274669',
    projectId: 'arzan-app',
    storageBucket: 'arzan-app.appspot.com',
    androidClientId:
        '140590274669-53hlokfdu84ffh2f085bc18h4dkkuc14.apps.googleusercontent.com',
    iosClientId:
        '140590274669-m12f35mpcsg6055rmp2qh2tarnv94m63.apps.googleusercontent.com',
    iosBundleId: 'afisha.arzan.tm',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBFoFfFL1wJRocXnhmlt53aBzHKki0PIiU",
    authDomain: "arzan-app.firebaseapp.com",
    projectId: "arzan-app",
    storageBucket: "arzan-app.appspot.com",
    messagingSenderId: "140590274669",
    appId: "1:140590274669:web:5620bf2de139dd067ec764",
    measurementId: "G-38BW1PG63B",
  );
}
